Update zlib version
joseluisq/rust-linux-darwin-builder pull request #25
Opened 2023-08-23 10:31 UTC by rjkroege

I found that I needed the new version of zlib and to fetch it from https for the Docker to build.

2023-08-23 10:44 UTC, joseluisq commented
Yep, every time there is a new release coming it supersedes the previous one like https://github.com/joseluisq/rust-linux-darwin-builder/pull/17. They do not preserve the tarballs history for some reason.

Probably we have to try to find out a second source.

2023-08-23 10:46 UTC, joseluisq commented
Oh, there are https://www.zlib.net/fossils/

2023-08-23 10:48 UTC, joseluisq requested changes

2023-08-23 10:48 UTC, joseluisq commented on Dockerfile
> +    && curl -LO "https://zlib.net/zlib-${ZLIB_VERSION}.tar.gz" \
Let's use this one to be consistent from now on. 

```suggestion
    && curl -LO "https://www.zlib.net/fossils/zlib-${ZLIB_VERSION}.tar.gz" \
```

2023-08-24 09:04 UTC, rjkroege commented
I applied your suggestion.

2023-08-24 10:57 UTC, joseluisq approved these changes

2023-08-24 10:59 UTC, merged